version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/l99_bot"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
